<?php
namespace FormPipe;

defined( 'ABSPATH' ) || exit;

/**
 * Tag-generator: dialog panels that insert form-tags into the editor.
 *
 * Modules register a panel during formpipe_init. Each panel has:
 *   - id, title, callback, features (display-block, etc.)
 *
 * The dialog is a hidden <dialog> shown via JavaScript. The button-bar
 * of "Generate Tag" buttons is rendered by print_buttons(); the dialog
 * contents by print_panels().
 */
final class TagGenerator {

	private static ?TagGenerator $instance = null;

	/** @var array<string,array{title:string,content:string,options:array,callback:callable}> */
	private array $panels = [];

	public static function get_instance(): self {
		if ( self::$instance === null ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	public function register(): void {
		add_action( 'formpipe_init', [ $this, 'register_panels' ], 15, 0 );
	}

	public function register_panels(): void {
		// Modules add panels via formpipe_add_tag_generator() during init.
		// We register one panel per core module.
		foreach ( [
			'text'      => __( 'Text field', 'formpipe' ),
			'email'     => __( 'Email', 'formpipe' ),
			'url'       => __( 'URL', 'formpipe' ),
			'tel'       => __( 'Telephone', 'formpipe' ),
			'textarea'  => __( 'Textarea', 'formpipe' ),
			'number'    => __( 'Number', 'formpipe' ),
			'date'      => __( 'Date', 'formpipe' ),
			'time'      => __( 'Time', 'formpipe' ),
			'select'    => __( 'Drop-down menu', 'formpipe' ),
			'checkbox'  => __( 'Checkboxes', 'formpipe' ),
			'radio'     => __( 'Radio buttons', 'formpipe' ),
			'acceptance'=> __( 'Acceptance', 'formpipe' ),
			'quiz'      => __( 'Quiz', 'formpipe' ),
			'file'      => __( 'File upload', 'formpipe' ),
			'hidden'    => __( 'Hidden field', 'formpipe' ),
			'submit'    => __( 'Submit button', 'formpipe' ),
		] as $id => $title ) {
			$this->add( $id, $title, [ $this, 'panel_for_' . str_replace( '-', '_', $id ) ], [ 'version' => '2' ] );
		}
	}

	public function add( string $id, string $title, callable $callback, array $options = [] ): bool {
		$id = trim( $id );

		if ( $id === '' || ! formpipe_is_name( $id ) ) {
			return false;
		}

		$this->panels[ $id ] = [
			'title'    => $title,
			'content'  => 'tag-generator-panel-' . $id,
			'options'  => $options,
			'callback' => $callback,
		];

		return true;
	}

	/** @return array<string,array> */
	public function panels(): array {
		return $this->panels;
	}

	public function print_buttons(): void {
		echo '<span id="tag-generator-list" class="hide-if-no-js">';

		foreach ( $this->panels as $id => $panel ) {
			printf(
				'<button type="button" class="button" data-taggen="open-dialog" data-target="%1$s" title="%2$s">%3$s</button> ',
				esc_attr( $panel['content'] ),
				esc_attr( sprintf( __( 'Generate %s tag', 'formpipe' ), $panel['title'] ) ),
				esc_html( $panel['title'] )
			);
		}

		echo '</span>';
	}

	public function print_panel( Form $form, array $panel ): void {
		$id     = array_search( $panel, $this->panels, true );
		$key    = is_string( $id ) ? $id : '';

		echo '<dialog id="' . esc_attr( $panel['content'] ) . '" class="formpipe-tag-dialog tag-generator-dialog">';
		echo '<form method="dialog" class="tag-generator-panel" data-id="' . esc_attr( $key ) . '" data-version="2">';

		$callback = $panel['callback'];
		if ( is_callable( $callback ) ) {
			$callback( $form, $panel['options'] + [ 'id' => $key, 'title' => $panel['title'], 'content' => $panel['content'] ] );
		}

		echo '<p class="formpipe-tag-buttons">';
		echo '<button type="button" class="button" data-taggen="close-dialog">' . esc_html__( 'Cancel', 'formpipe' ) . '</button> ';
		echo '<button type="button" class="button button-primary" data-taggen="insert-tag">' . esc_html__( 'Insert Tag', 'formpipe' ) . '</button>';
		echo '</p>';

		echo '</form>';
		echo '</dialog>';
	}

	/* --- Panel callbacks (very small — actual UI is generated by JS) --- */

	public function panel_for_text( Form $form, array $options ): void {
		$this->panel_skeleton( [
			[ 'name', __( 'Name (required)', 'formpipe' ), 'text', 'your-name' ],
			[ 'type', __( 'Field type', 'formpipe' ), 'select', 'text', [
				'text' => __( 'Text', 'formpipe' ),
				'email'=> __( 'Email', 'formpipe' ),
				'url'  => __( 'URL', 'formpipe' ),
				'tel'  => __( 'Telephone', 'formpipe' ),
			] ],
			[ 'required', __( 'Required', 'formpipe' ), 'checkbox' ],
			[ 'placeholder', __( 'Placeholder', 'formpipe' ), 'text' ],
			[ 'default', __( 'Default value', 'formpipe' ), 'text' ],
			[ 'class', __( 'Class', 'formpipe' ), 'text', 'formpipe-field' ],
			[ 'id', __( 'Id', 'formpipe' ), 'text' ],
		], 'text' );
	}

	public function panel_for_textarea( Form $form, array $options ): void {
		$this->panel_skeleton( [
			[ 'name', __( 'Name (required)', 'formpipe' ), 'text', 'your-message' ],
			[ 'required', __( 'Required', 'formpipe' ), 'checkbox' ],
			[ 'placeholder', __( 'Placeholder', 'formpipe' ), 'text' ],
			[ 'default', __( 'Default value', 'formpipe' ), 'textarea' ],
			[ 'rows', __( 'Rows', 'formpipe' ), 'number', '5' ],
			[ 'cols', __( 'Cols', 'formpipe' ), 'number', '40' ],
		], 'textarea' );
	}

	public function panel_for_number( Form $form, array $options ): void {
		$this->panel_skeleton( [
			[ 'name', __( 'Name (required)', 'formpipe' ), 'text', 'age' ],
			[ 'required', __( 'Required', 'formpipe' ), 'checkbox' ],
			[ 'min', __( 'Min', 'formpipe' ), 'number', '0' ],
			[ 'max', __( 'Max', 'formpipe' ), 'number', '100' ],
			[ 'step', __( 'Step', 'formpipe' ), 'number', '1' ],
		], 'number' );
	}

	public function panel_for_date( Form $form, array $options ): void {
		$this->panel_skeleton( [
			[ 'name', __( 'Name (required)', 'formpipe' ), 'text', 'birthday' ],
			[ 'required', __( 'Required', 'formpipe' ), 'checkbox' ],
			[ 'min', __( 'Min (YYYY-MM-DD)', 'formpipe' ), 'text' ],
			[ 'max', __( 'Max (YYYY-MM-DD)', 'formpipe' ), 'text' ],
		], 'date' );
	}

	public function panel_for_time( Form $form, array $options ): void {
		$this->panel_skeleton( [
			[ 'name', __( 'Name (required)', 'formpipe' ), 'text', 'meeting-time' ],
			[ 'required', __( 'Required', 'formpipe' ), 'checkbox' ],
		], 'time' );
	}

	public function panel_for_email( Form $form, array $options ): void {
		$this->panel_for_text( $form, $options );
	}

	public function panel_for_url( Form $form, array $options ): void {
		$this->panel_for_text( $form, $options );
	}

	public function panel_for_tel( Form $form, array $options ): void {
		$this->panel_for_text( $form, $options );
	}

	public function panel_for_select( Form $form, array $options ): void {
		$this->panel_skeleton( [
			[ 'name', __( 'Name (required)', 'formpipe' ), 'text', 'menu' ],
			[ 'options', __( 'Options (one per line)', 'formpipe' ), 'textarea', "Red\nBlue" ],
			[ 'multiple', __( 'Allow multiple selections', 'formpipe' ), 'checkbox' ],
			[ 'include_blank', __( 'Include a blank option', 'formpipe' ), 'checkbox' ],
		], 'select' );
	}

	public function panel_for_checkbox( Form $form, array $options ): void {
		$this->panel_skeleton( [
			[ 'name', __( 'Name (required)', 'formpipe' ), 'text', 'topics' ],
			[ 'options', __( 'Options (one per line)', 'formpipe' ), 'textarea', "Topic A\nTopic B" ],
			[ 'exclusive', __( 'Single checkbox (radio-style)', 'formpipe' ), 'checkbox' ],
		], 'checkbox' );
	}

	public function panel_for_radio( Form $form, array $options ): void {
		$this->panel_skeleton( [
			[ 'name', __( 'Name (required)', 'formpipe' ), 'text', 'choice' ],
			[ 'options', __( 'Options (one per line)', 'formpipe' ), 'textarea', "Yes\nNo" ],
		], 'radio' );
	}

	public function panel_for_acceptance( Form $form, array $options ): void {
		$this->panel_skeleton( [
			[ 'name', __( 'Name (required)', 'formpipe' ), 'text', 'accept-terms' ],
			[ 'label', __( 'Label (optional)', 'formpipe' ), 'text', 'I accept the terms.' ],
			[ 'required', __( 'Required', 'formpipe' ), 'checkbox', true ],
		], 'acceptance' );
	}

	public function panel_for_quiz( Form $form, array $options ): void {
		$this->panel_skeleton( [
			[ 'name', __( 'Name (required)', 'formpipe' ), 'text', 'quiz-q' ],
			[ 'question', __( 'Question and answer (Question|Answer)', 'formpipe' ), 'text', '1+1=?|2' ],
		], 'quiz' );
	}

	public function panel_for_file( Form $form, array $options ): void {
		$this->panel_skeleton( [
			[ 'name', __( 'Name (required)', 'formpipe' ), 'text', 'attachment' ],
			[ 'accept', __( 'Accepted MIME types', 'formpipe' ), 'text', 'image/*,application/pdf' ],
			[ 'limit', __( 'Size limit (e.g. 2mb)', 'formpipe' ), 'text', '5mb' ],
			[ 'filetypes', __( 'File extensions (comma-separated)', 'formpipe' ), 'text', 'jpg,png,pdf' ],
		], 'file' );
	}

	public function panel_for_hidden( Form $form, array $options ): void {
		$this->panel_skeleton( [
			[ 'name', __( 'Name (required)', 'formpipe' ), 'text', 'source' ],
			[ 'default', __( 'Default value', 'formpipe' ), 'text' ],
		], 'hidden' );
	}

	public function panel_for_submit( Form $form, array $options ): void {
		$this->panel_skeleton( [
			[ 'label', __( 'Button label', 'formpipe' ), 'text', __( 'Send', 'formpipe' ) ],
			[ 'class', __( 'Class', 'formpipe' ), 'text', 'formpipe-submit' ],
		], 'submit' );
	}

	private function panel_skeleton( array $fields, string $basetype ): void {
		echo '<div class="formpipe-tag-fields" data-basetype="' . esc_attr( $basetype ) . '">';
		foreach ( $fields as $i => $f ) {
			$name = (string) $f[0];
			$label = (string) $f[1];
			$type = (string) ( $f[2] ?? 'text' );
			$default = (string) ( $f[3] ?? '' );
			$choices = is_array( $f[4] ?? null ) ? $f[4] : [];

			$id = 'tag-' . $basetype . '-' . $name . '-' . $i;

			echo '<p><label for="' . esc_attr( $id ) . '">' . esc_html( $label ) . '</label><br />';

			if ( $type === 'select' ) {
				echo '<select id="' . esc_attr( $id ) . '" name="' . esc_attr( $name ) . '">';
				foreach ( $choices as $v => $l ) {
					echo '<option value="' . esc_attr( $v ) . '">' . esc_html( $l ) . '</option>';
				}
				echo '</select>';
			} elseif ( $type === 'checkbox' ) {
				echo '<label><input type="checkbox" id="' . esc_attr( $id ) . '" name="' . esc_attr( $name ) . '" value="1" /> ' . esc_html__( 'Yes', 'formpipe' ) . '</label>';
			} elseif ( $type === 'textarea' ) {
				echo '<textarea id="' . esc_attr( $id ) . '" name="' . esc_attr( $name ) . '" rows="4" class="large-text">' . esc_textarea( $default ) . '</textarea>';
			} else {
				echo '<input type="' . esc_attr( $type ) . '" id="' . esc_attr( $id ) . '" name="' . esc_attr( $name ) . '" value="' . esc_attr( $default ) . '" class="regular-text" />';
			}

			echo '</p>';
		}
		echo '</div>';
	}
}

/**
 * Convenience for module authors to register their own tag-generator panels.
 */
function formpipe_add_tag_generator( string $name, string $title, callable $callback, array $options = [] ): bool {
	return TagGenerator::get_instance()->add( $name, $title, $callback, $options );
}
